name: CI/CD Pipeline
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Updated to v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4  # Updated to v4
        with:
          distribution: 'temurin'  # Specify the distribution (e.g., Temurin, Amazon Corretto, etc.)
          java-version: '23'
      - name: Build with Maven
        run: mvn clean package
      - name: Archive JAR
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: library-jar
          path: target/soams.jar
